### ISSUE TITLE
No filtering done in the queryApiLogByOrderReferenceAndType method

### ISSUE THREAD

**Issue by philipposkard** [spryker-eco/arvato-rss#17]
The `queryApiLogByOrderReferenceAndType`  does not filter the query by `$orderReference` and `$type` as the Method name suggests. The parameters are not used. Please consider this as an issue for the next release.

**Comment by tvaleriy** [comment]
Hi Philip,

my name is Valerii and I'm a support engineer in Spryker.
Thank you for the report, internal ticket is created and I will notify here when it's fixed and released.
But normally we aren't monitoring repositories for created PR's or issues. So please use http://support.spryker.com next time.
Thank you for your understanding.

Best regards,
Valerii

**Comment by tvaleriy** [comment]
Hi @philipposkard, this should be fixed in https://github.com/spryker-eco/arvato-rss/releases/tag/2.1.0. Please update.
